server:
#  port: 8008
  port: 0

spring:
  application:
    name: point-service
  datasource:
    url: ${point.mariadb.local.url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${point.mariadb.local.username}
    password: ${point.mariadb.local.password}
  jpa:
    #    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true

eureka:
  instance:
    # hostname: ${EUREKA_HOSTNAME:localhost} # 외부에서 접근 가능한 호스트 이름 또는 IP
    instance-id: ${EUREKA_HOSTNAME:localhost}:${spring.application.instance_id:${random.value}}# 외부에서 접근 가능한 호스트 이름 또는 IP
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${point.eureka.service-url}
