server:
  port: 0

spring:
  config:
    import: secret/application-secret.yml
  application:
    name: advertisement-service
  datasource:
    url: ${advertisement.mariadb.local.url}
    driver-class-nacme: ${mariadb-advertisement.driver-class-name}
    username: ${advertisement.mariadb.local.username}
    password: ${advertisement.mariadb.local.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true

eureka:
  instance:
    # hostname: ${EUREKA_HOSTNAME:localhost} # 외부에서 접근 가능한 호스트 이름 또는 IP
    instance-id: ${EUREKA_HOSTNAME:localhost}:${spring.application.instance_id:${random.value}}# 외부에서 접근 가능한 호스트 이름 또는 IP
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${advertisement.eureka.service-url}